// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Model;

namespace StudentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230907180708_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentAPI.Courses", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fees")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "C#",
                            Fees = 500,
                            StartingDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = ".NET",
                            Fees = 600,
                            StartingDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "SQL Server",
                            Fees = 800,
                            StartingDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Angular",
                            Fees = 700,
                            StartingDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StudentAPI.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(1996, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "neha2208patel@gmail.com",
                            Firstname = "Neha",
                            Gender = 1,
                            Lastname = "Patel"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(1994, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "steveorth@gmail.com",
                            Firstname = "Steve",
                            Gender = 0,
                            Lastname = "Orth"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(1993, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "natiajohn@gmail.com",
                            Firstname = "Natia",
                            Gender = 1,
                            Lastname = "John"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateTime(1995, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "samanthabarely@gmail.com",
                            Firstname = "Samantha",
                            Gender = 1,
                            Lastname = "Barely"
                        },
                        new
                        {
                            StudentId = 5,
                            DateOfBirth = new DateTime(1996, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "zackperry@gmail.com",
                            Firstname = "Zack",
                            Gender = 0,
                            Lastname = "Perry"
                        });
                });

            modelBuilder.Entity("StudentAPI.StudentEnrolment", b =>
                {
                    b.Property<int>("EnrolmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrolmentId");

                    b.ToTable("StudentEnrolments");

                    b.HasData(
                        new
                        {
                            EnrolmentId = 1,
                            CourseId = 1,
                            RegisteredDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Fall 2023",
                            StudentId = 1
                        },
                        new
                        {
                            EnrolmentId = 2,
                            CourseId = 1,
                            RegisteredDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Fall 2023",
                            StudentId = 2
                        },
                        new
                        {
                            EnrolmentId = 3,
                            CourseId = 3,
                            RegisteredDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Fall 2023",
                            StudentId = 1
                        },
                        new
                        {
                            EnrolmentId = 4,
                            CourseId = 4,
                            RegisteredDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Fall 2023",
                            StudentId = 1
                        },
                        new
                        {
                            EnrolmentId = 5,
                            CourseId = 4,
                            RegisteredDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Spring 2024",
                            StudentId = 2
                        },
                        new
                        {
                            EnrolmentId = 6,
                            CourseId = 4,
                            RegisteredDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Spring 2024",
                            StudentId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
